# Generated by Django 5.1.7 on 2025-03-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
